accounts/urls.py
from django.urls import path

from .views import SignUpView


urlpatterns = [
    path("signup/", SignUpView.as_view(), name="signup"),
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include

from mysite import settings


urlpatterns = [
    path("spaceboard/", include("spaceboard.urls")),
    path('admin/', admin.site.urls),
    path("accounts/", include("accounts.urls")),
    path("accounts/", include("django.contrib.auth.urls")),
]

spaceboard/urls.py
from django.urls import path

from . import views

app_name = "spaceboard"
urlpatterns = [
    path("", views.RoomView.as_view(), name="overview"),
    path("<int:pk>/", views.DetailView.as_view(), name="detail"),
    path("dashboard/", views.DashboardView.as_view(), name="dashboard"),
    path("<int:pk>/booking/", views.BookingView.as_view(), name="booking"),
    path("<int:pk>/booking/book-room/", views.booking_view, name="book-room"),
    path("<int:pk>/booking-success/", views.booking_success, name="booking-success"),
    path("api/bookings/", views.bookings_api, name="bookings-api"),
    path("dashboard/delete/<int:pk>/", views.delete, name="delete"),
    path("dashboard/delete/deletion-success/", views.deletion_success, name="deletion-success"),
    path("dashboard/edit/<int:pk>/", views.EditView.as_view(), name="edit"),
]

accounts/models.py
from django.db import models

# Create your models here.

spaceboard/models.py
from django.db import models

class Room(models.Model):
    id = models.AutoField(primary_key=True)
    name = models.CharField(max_length=200)
    capacity = models.IntegerField()

    def __str__(self):
        return self.name


class Booking(models.Model):
    room = models.ForeignKey(Room, on_delete=models.CASCADE)
    user_id = models.IntegerField()
    start = models.DateTimeField()
    end = models.DateTimeField()

    def __str__(self):
        return str(self.id)

    @classmethod
    def book(cls, room, user_id, start, end):
        booking = cls.objects.create(
            room=room,
            user_id=user_id,
            start=start,
            end=end,
        )
        booking.save()
        return booking
    

spaceboard/forms.py
from django import forms
from .models import Booking


class EditingForm(forms.ModelForm):
    class Meta:
        model = Booking
        fields = ['room', 'start', 'end']
        widgets = {
            'start': forms.DateTimeInput(attrs={
                'type': 'datetime-local',
                'step': 1800
            }),
            'end': forms.DateTimeInput(attrs={
                'type': 'datetime-local',
                'step': 1800
            }),
        }

accounts/views.py
from django.contrib.auth.forms import UserCreationForm
from django.urls import reverse_lazy
from django.views.generic import CreateView


class SignUpView(CreateView):
    form_class = UserCreationForm
    success_url = reverse_lazy("login")
    template_name = "registration/signup.html"

spaceboard/views.py
from datetime import date, time, datetime

from django import forms
from django.db.models import F
from django.http import HttpResponse, HttpResponseRedirect, JsonResponse
from django.shortcuts import get_object_or_404, redirect, render
from django.urls import reverse, reverse_lazy
from django.views import generic

from .models import Room, Booking
from .forms import EditingForm


class RoomView(generic.ListView):
    template_name = "spaceboard/overview.html"
    context_object_name = "room_overview"

    def get_queryset(self):
        return Room.objects.order_by("capacity")



class DetailView(generic.DetailView):
    model = Room
    template_name = "spaceboard/detail.html"



class DashboardView(generic.ListView):
    model = Room
    template_name = "spaceboard/dashboard.html"
    context_object_name = "bookings"

    def get_queryset(self):
        return Booking.objects.filter(user_id=self.request.user.id)



class BookingView(generic.DetailView):
    model = Room
    template_name = "spaceboard/booking.html"



class EditView(generic.UpdateView):
    model = Booking
    form_class = EditingForm
    template_name = "spaceboard/edit.html"

    def get_success_url(self):
        return reverse_lazy('dashboard')
    
    def get_form(self, form_class=None):
        form = super().get_form(form_class)
        form.fields['start'].input_formats = ['%Y-%m-%dT%H:%M']
        form.fields['end'].input_formats = ['%Y-%m-%dT%H:%M']
        return form



def booking_view(request, pk):
    room = get_object_or_404(Room, pk=pk)
    if request.method == 'POST':
        Booking.book(
            room=room,
            user_id=request.user.id,
            start=request.POST['start'],
            end=request.POST['end']
        )
        return redirect('../../booking-success')

    

def booking_success(request, pk):
    room = get_object_or_404(Room, pk=pk)
    return render(request, 'spaceboard/booking_success.html', {'room': room})



def bookings_api(request):
    room_id = request.GET.get('room')
    user_id = request.GET.get('user')

    bookings = Booking.objects.all()
    if room_id:
        bookings = bookings.filter(room=room_id)
        color = '#111111'
    else:
        if user_id:
            bookings = bookings.filter(user_id=user_id)
            color = '#13711e'

    events = []
    for booking in bookings:
        events.append({
            'id': booking.id,
            'room': f'{booking.room.name}',
            'start': booking.start.isoformat(),
            'end': booking.end.isoformat(),
            'color': color,
            'extendedProps': {
                'room': booking.room.name,
            }
        })
    return JsonResponse(events, safe=False)



def deletion_success(request):
    return render(request, 'spaceboard/deletion_success.html')


def delete(request, pk):
    booking = Booking.objects.get(id=pk)
    booking.delete()
    return redirect('../deletion-success/')

spaceboard/templates/base.html
<!DOCTYPE html>
<html lang="de">
<head>
    {% load static %}
    <meta charset="UTF-8">
    <link rel="stylesheet" href="{% static 'style.css' %}">
</head>
<body>
    <!-- Navigation -->
    <nav>
        <ul>
            <li><a href="{% url 'spaceboard:overview' %}">Raumübersicht</a></li>
            <li><a href="{% url 'spaceboard:dashboard' %}">Dashboard</a></li>
            <li>
                <form method="post" action="{% url 'logout' %}">
                    {% csrf_token %}
                    <button type="submit">Logout</button>
                </form>
            </li>
            <p style="float: right; color: white">Eingelogt als: {{ request.user }}</p>
        </ul>
        
        
    </nav>

    <hr>

    <!-- Inhalt von Unterseiten -->
    <div class="page-wrapper">
        <div class="spacer"></div>
            <div class="content">
                {% block content %}
                <!-- Seiteninhalt hier -->
                {% endblock %}
            </div>
        <div class="spacer"></div>
    </div>
</body>
</html>

spaceboard/templates/spaceboard/booking.html
{% extends "base.html" %}

{% block content %}
    <h1>Buchung: {{ room.name }}</h1>
    
    <form method="post" action="{% url 'spaceboard:book-room' room.id %}" style="float: left">
        {% csrf_token %}
        <label for="timeslot">Wählen Sie einen Zeitraum im Kalender: </label>
        <br><br>
        <label>Von </label>
        <input type="datetime-local" name="start" id="start" required readonly>
        <label>Bis </label> 
        <input type="datetime-local" name="end" id="end" required readonly> 
        <br><br>
        <button type="submit">Buchen</button>
    </form>
    <div style="float: right">
        <p style="color: black">Raum belegt</p>
        <p style="color: #13711e">Eigene Reservierungen</p>
    </div>
    
    <br><br><br><br><br><br><br>

    <link href='https://cdn.jsdelivr.net/npm/fullcalendar@6.1.8/index.global.min.css' rel='stylesheet' />
    <script src='https://cdn.jsdelivr.net/npm/fullcalendar@6.1.8/index.global.min.js'></script>

    <div id='calendar' style="max-width: 900px; margin: 40px auto; height: 600px;"></div>

    <script>
        let selectedStart = null;
        let selectedEnd = null;

        document.addEventListener('DOMContentLoaded', function() {
        var calendarEl = document.getElementById('calendar');
        var calendar = new FullCalendar.Calendar(calendarEl, {
            initialView: 'timeGridWeek',
            eventSources: [
                {
                    url: '{% url "spaceboard:bookings-api" %}?room={{ object.pk }}',
                    color: '#525252',
                    textColor: 'white',
                },
                {
                    url: '{% url "spaceboard:bookings-api" %}?user={{ request.user.id }}',
                    color: '#66c7f4',
                    textColor: 'white',
                }
            ],
            //events: '{% url "spaceboard:bookings-api" %}?room={{ object.pk }}',
            headerToolbar: {
            left: 'prev,next today',
            center: 'title',
            right: 'timeGridWeek,timeGridDay',
            },
            height: 569,
            nowIndicator: true,
            locale: 'de',
            businessHours: {
                daysOfWeek: [ 1, 2, 3, 4, 5 ]
            },
            weekends: false,
            slotMinTime: "08:00",
            slotMaxTime: "18:00",
            allDaySlot: false,
            snapDuration: "00:15:00",
            selectable: true,
            selectOverlap: false,
            selectConstraint: {
                startTime: "8:00",
                endTime: "18:00"
            },
            select: function(info) {
                function pad(n) {
                    return n < 10 ? '0' + n : n;
                }
                function toDatetimeLocalString(date) {
                    return date.getFullYear() + '-' +
                            pad(date.getMonth() + 1) + '-' +
                            pad(date.getDate()) + 'T' +
                            pad(date.getHours()) + ':' +
                            pad(date.getMinutes());
                }
                document.getElementById('start').value = toDatetimeLocalString(info.start);
                document.getElementById('end').value = toDatetimeLocalString(info.end);
            }
        });
        calendar.render();
        });
    </script>


{% endblock %}

spaceboard/templates/spaceboard/booking_success.html
{% extends "base.html" %}

{% block content %}

    <center>
        <h1>Die Buchung war erfolgreich!</h1>
        <a href="{% url 'spaceboard:detail' room.id %}" class="outlined">OK</a>
    </center>

{% endblock %}

spaceboard/templates/spaceboard/dashboard.html
{% extends "base.html" %}

{% block content %}

    <h1>Hier findest du deine Buchungen:</h1>

    <link href='https://cdn.jsdelivr.net/npm/fullcalendar@6.1.8/main.min.css' rel='stylesheet' />
    <script src='https://cdn.jsdelivr.net/npm/fullcalendar@6.1.8/index.global.min.js'></script>

    <div id='calendar' style="max-width: 900px; margin: 40px auto; height: 600px;"></div>

    <div id="event-info"
        style="display: none; position: absolute; background: #f9f9f9; border: 1px solid #ccc; padding: 10px; box-shadow: 0 2px 8px rgba(0,0,0,0.2); z-index: 1000;">
        <input type="hidden" id="booking-id">
        <strong>Raum: <span id="room-name"></span></strong><br>
        <span>Start: <span id="start-time"></span></span><br>
        <span>Ende: <span id="end-time"></span></span>
        <br><br>
        <div style="display: inline-block; margin-right: 10px;">
            <a href="#" class="outlined close-link">Schließen</a>
        </div>
        <div style="display: inline-block; margin-right: 10px;">
            <a href="{% url 'spaceboard:dashboard' %}" class="outlined edit-link">Bearbeiten</a>
        </div>
        <div style="display: inline-block; margin-right: 10px;">
            <a href="#" class="outlined delete-link">Löschen</a>
        </div>
        
    </div>

    <script>
        document.addEventListener('DOMContentLoaded', function() {
            var calendarEl = document.getElementById('calendar');
            var calendar = new FullCalendar.Calendar(calendarEl, {
                initialView: 'timeGridWeek',
                events: '{% url "spaceboard:bookings-api" %}?user={{ request.user.id }}',
                headerToolbar: {
                left: 'prev,next today',
                center: 'title',
                right: 'timeGridWeek,timeGridDay',
                },
                height: 569,
                nowIndicator: true,
                locale: 'de',
                businessHours: {
                    daysOfWeek: [ 1, 2, 3, 4, 5 ]
                },
                weekends: false,
                slotMinTime: "08:00",
                slotMaxTime: "18:00",
                allDaySlot: false,
                selectable: true,
                eventClick: function(info) {
                    const id = info.event.id;
                    const room = info.event.extendedProps.room;
                    const start = info.event.start.toLocaleString();
                    const end = info.event.end ? info.event.end.toLocaleString() : 'Offen';

                    document.querySelector('.close-link').addEventListener('click', function (e) {
                        e.preventDefault();
                        document.getElementById('event-info').style.display = 'none';
                    });

                    document.getElementById('booking-id').value = id;
                    document.getElementById('room-name').textContent = room;
                    document.getElementById('start-time').textContent = start;
                    document.getElementById('end-time').textContent = end;

                    const box = document.getElementById('event-info');
                    box.style.left = info.jsEvent.pageX + 'px';
                    box.style.top = info.jsEvent.pageY + 'px';
                    box.style.display = 'block';

                    info.jsEvent.preventDefault();

                    document.querySelector('#event-info .edit-link').href = `/spaceboard/dashboard/edit/${id}/`;
                    document.querySelector('#event-info .delete-link').href = `/spaceboard/dashboard/delete/${id}/`;
                }
            });
            calendar.render();
        });
    </script>

    {% if request.user.is_superuser %}
        <center><a href="{% url 'admin:index' %}" class="outlined">Zur Admin-Seite</a></center>
    {% endif %}
    
{% endblock %}

spaceboard/templates/spaceboard/deletion_success.html
{% extends "base.html" %}

{% block content %}

    <center>
        <h1>Die Buchung wurde gelöscht!</h1>
        <a href="{% url 'spaceboard:dashboard' %}" class="outlined">OK</a>
    </center>

{% endblock %}

spaceboard/templates/spaceboard/detail.html
{% extends "base.html" %}

{% block content %}
    <h1>{{ room.name }}</h1>
    <ul>
        <li>Kapazität: {{ room.capacity }}</li>
    </ul>
    <center><a href="{% url 'spaceboard:booking' room.id %}" class="outlined">Buchen</a></center></h1>
    

    <link href='https://cdn.jsdelivr.net/npm/fullcalendar@6.1.8/index.global.min.css' rel='stylesheet' />
    <script src='https://cdn.jsdelivr.net/npm/fullcalendar@6.1.8/index.global.min.js'></script>

    <div id='calendar' style="max-width: 900px; margin: 40px auto; height: 600px;"></div>

    <script>
        document.addEventListener('DOMContentLoaded', function() {
        var calendarEl = document.getElementById('calendar');
        var calendar = new FullCalendar.Calendar(calendarEl, {
            initialView: 'timeGridWeek',
            events: '{% url "spaceboard:bookings-api" %}?room={{ room.id }}',
            headerToolbar: {
                left: 'prev,next today',
                center: 'title',
                right: 'timeGridWeek,timeGridDay',
            },
            height: 569,
            nowIndicator: true,
            locale: 'de',
            businessHours: {
                daysOfWeek: [ 1, 2, 3, 4, 5 ]
            },
            weekends: false,
            slotMinTime: "08:00",
            slotMaxTime: "18:00",
            allDaySlot: false
        });
        calendar.render();
        });
    </script>

{% endblock %}

spaceboard/templates/spaceboard/edit.html
{% extends "base.html" %}

{% block content %}

    <h1>Buchung bearbeiten</h1>

    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <!--<select name="rooms" id="rooms">
            {% for room in rooms %}
                <option value=room.name>room.name</option>
            {% endfor %}
        </select>-->
        <button type="submit">Speichern</button>
    </form>
    

{% endblock %}

spaceboard/templates/spaceboard/overview.html
{% extends "base.html" %}

{% block content %}
    <h1>Raumübersicht</h1>
    <div style="float: left; width: calc(70% - 1rem);">
        {% if room_overview %}
            <dl class="room-grid">
            {% for room in room_overview %}
                <div class="container">
                    <dt><a href="{% url 'spaceboard:detail' room.id %}" class="outlined">{{ room.name }}</a></dt>
                    <br>
                    <dd>Kapazität: {{ room.capacity }}</dd>
                </div>
                <br>
            {% endfor %}
            </dl>
        {% else %}
            <p>No rooms are available.</p>
        {% endif %}
    </div>
        
    <div style="float: right; width: calc(30% - 1rem);">
        <h2>Filter</h2>
        <br>
        Kapazität: <input type="number" id="lowestCapacity" style="width: 40px"> - <input type="number" id="highestCapacity" style="width: 40px">
        <br><br>
        Datum: <input type="date" id="date">
        <br><br>
        Zeitraum: <input type="time" id="startTime"> - <input type="time" id="endTime">
        <br><br>
        <button id="filterButton">Suchen</button>
    </div>
    
    <script>
        document.getElementById("filterButton").addEventListener("click", function () {
            const minCap = parseInt(document.getElementById("lowestCapacity").value) || 0;
            const maxCap = parseInt(document.getElementById("highestCapacity").value) || Infinity;

            document.querySelectorAll(".room-grid .container").forEach(function (card) {
                const capacityText = card.querySelector("dd").innerText;
                const match = capacityText.match(/\d+/);
                const capacity = match ? parseInt(match[0]) : 0;

                if (capacity >= minCap && capacity <= maxCap) {
                    card.style.display = "block"; // anzeigen
                } else {
                    card.style.display = "none"; // ausblenden
                }
            });    
        });
    </script>
{% endblock %}